[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:fastapi]
command=uv run uvicorn src.main:app --host 0.0.0.0 --port %(ENV_PORT)s
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=uv run celery -A src.tasks.celery_app worker --loglevel=info
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
