[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:fastapi]
; Hugging Face Spaces requires exposing port 7860
command=uv run uvicorn src.main:app --host 0.0.0.0 --port 7860
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:celery]
command=uv run celery -A src.tasks.celery_app worker --loglevel=info
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
