[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:fastapi]
command=uv run uvicorn rag_project.main:app --host 0.0.0.0 --port %(ENV_PORT)s
autostart=true
autorestart=true
stderr_logfile=/tmp/fastapi.err.log
stdout_logfile=/tmp/fastapi.out.log

[program:celery]
command=uv run celery -A rag_project.celery_app worker --loglevel=info
autostart=true
autorestart=true
stderr_logfile=/tmp/celery.err.log
stdout_logfile=/tmp/celery.out.log
