"""add_file_path_to_documents

Revision ID: cfa0c4e9e2b9
Revises: 92b667fc7d79
Create Date: 2026-09-28 16:52:31.733106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa0c4e9e2b9'
down_revision: Union[str, Sequence[str], None] = '92b667fc7d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
