import { useState, useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { X } from 'lucide-react';
import { Badge } from '../../components/ui/Badge';
import { DocumentModal } from '../../components/ui/DocumentModal';
import type { Message } from '../../store/chatStore';
import { useChatStore } from '../../store/chatStore';
import styles from './MessageBubble.module.css';

interface MessageBubbleProps {
  message: Message;
}

interface OpenDocState {
  docId: string;
  filename: string;
  highlightText?: string;
}

function cleanMessageContent(raw: string): string {
  if (!raw) return '';
  // Strip trailing "## Sources" or "Sources" section generated by LLMs
  return raw.replace(/(?:\r?\n|^)#{0,3}\s*Sources\s*[\r\n]+(?:\[\d+\][\s\S]*)$/i, '').trimEnd();
}

function formatInlineCitations(text: string): string {
  if (!text) return '';
  // Convert [1], [2] citations into custom markdown links [1](#cite-1)
  return text.replace(/(?<!\[)\[(\d+)\](?!\]|\()/g, '[$1](#cite-$1)');
}

export function MessageBubble({ message }: MessageBubbleProps) {
  const isUser = message.role === 'user';
  const [openCitation, setOpenCitation] = useState<number | null>(null);
  const [openDoc, setOpenDoc] = useState<OpenDocState | null>(null);

  // Determine the thinking state: streaming but no content yet (pre-synthesizer)
  const pipeline = useChatStore((s) => s.pipeline);
  const isThinking =
    message.isStreaming &&
    !message.content &&
    pipeline.activeStep !== 'synthesizer';

  const cleanedContent = useMemo(() => cleanMessageContent(message.content || ''), [message.content]);
  const formattedContent = useMemo(() => formatInlineCitations(cleanedContent), [cleanedContent]);

  const citedIndices = useMemo(() => {
    if (!message.content) return new Set<number>();
    const matches = Array.from(message.content.matchAll(/(?<!\[)\[(\d+)\](?!\]|\()/g));
    const set = new Set<number>();
    for (const m of matches) {
      const idx = parseInt(m[1], 10) - 1;
      if (idx >= 0 && (!message.citations || idx < message.citations.length)) {
        set.add(idx);
      }
    }
    return set;
  }, [message.content, message.citations]);

  const displayedCitations = useMemo(() => {
    if (!message.citations || message.citations.length === 0) return [];
    if (citedIndices.size === 0) {
      return message.citations.map((c, i) => ({ citation: c, index: i }));
    }
    return message.citations
      .map((c, i) => ({ citation: c, index: i }))
      .filter(({ index }) => citedIndices.has(index));
  }, [message.citations, citedIndices]);

  const handleCitationClick = (index: number) => {
    const citation = message.citations?.[index];
    if (!citation) return;

    // For document chunks that have a doc_id, open the document modal
    if (citation.source_type === 'document_chunk' && citation.metadata?.doc_id) {
      const docId = citation.metadata.doc_id as string;
      // filename may be in metadata or we fall back to a generic name
      const filename = (citation.metadata?.filename as string) || `Document`;
      setOpenDoc({ docId, filename, highlightText: citation.content });
      return;
    }

    // For graph nodes or chunks without a stored file, toggle inline panel
    setOpenCitation(openCitation === index ? null : index);
  };

  return (
    <div className={[styles.wrapper, isUser ? styles.user : styles.assistant].join(' ')}>
      <div className={styles.bubble}>
        {/* Content */}
        {isUser ? (
          <p className={styles.userText}>{message.content || ''}</p>
        ) : (
          <div className="markdown-body">
            {isThinking ? (
              <span className={styles.thinking}>
                <span />
                <span />
                <span />
              </span>
            ) : (
              <>
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  components={{
                    a: ({ href, children, ...props }) => {
                      if (href?.startsWith('#cite-')) {
                        const idx = parseInt(href.replace('#cite-', ''), 10) - 1;
                        return (
                          <button
                            type="button"
                            className={styles.inlineCitation}
                            title={`Open source [${idx + 1}]`}
                            onClick={(e) => {
                              e.preventDefault();
                              e.stopPropagation();
                              handleCitationClick(idx);
                            }}
                          >
                            [{children}]
                          </button>
                        );
                      }
                      return (
                        <a href={href} target="_blank" rel="noopener noreferrer" {...props}>
                          {children}
                        </a>
                      );
                    },
                  }}
                >
                  {formattedContent}
                </ReactMarkdown>
                {message.isStreaming && <span className={styles.cursor} aria-hidden />}
              </>
            )}
          </div>
        )}

        {/* Metadata footer (only on completed assistant messages) */}
        {!isUser && !message.isStreaming && (
          <div className={styles.meta}>
            {message.routeTaken && (
              <Badge route={message.routeTaken} size="sm">
                {String(message.routeTaken).replace('_', ' ')}
              </Badge>
            )}
            {message.latencyMs !== undefined && (
              <span className={styles.stat}>{message.latencyMs}ms</span>
            )}
            {message.tokens?.total !== undefined && message.tokens.total > 0 && (
              <span className={styles.stat}>{message.tokens.total.toLocaleString()} tokens</span>
            )}
            {message.hallucination_flag && (
              <Badge variant="amber" size="sm">hallucination flag</Badge>
            )}
          </div>
        )}

        {/* Citations — compact clickable badges */}
        {!isUser && !message.isStreaming && displayedCitations.length > 0 && (
          <div className={styles.citationsSection}>
            <div className={styles.citations}>
              <span className={styles.citationsLabel}>Sources</span>
              {displayedCitations.map(({ citation: c, index: i }) => (
                <button
                  key={i}
                  type="button"
                  className={[styles.citation, openCitation === i ? styles.citationActive : ''].join(' ')}
                  title={
                    c.source_type === 'document_chunk' && c.metadata?.doc_id
                      ? 'Click to open source document'
                      : 'Click to view source content'
                  }
                  onClick={() => handleCitationClick(i)}
                >
                  <Badge variant={c.source_type === 'graph_node' ? 'violet' : 'cyan'} size="sm">
                    [{i + 1}] {c.source_type === 'graph_node' ? 'Graph' : 'Doc'}
                  </Badge>
                </button>
              ))}
            </div>

            {/* Inline panel — only for graph nodes or doc chunks without a stored file */}
            {openCitation !== null && message.citations?.[openCitation] && (
              <div className={styles.citationPanel}>
                <div className={styles.citationPanelHeader}>
                  <span className={styles.citationPanelTitle}>
                    [{openCitation + 1}] {message.citations[openCitation].source_type === 'graph_node' ? 'Graph Node' : 'Document Chunk'}
                  </span>
                  <button
                    type="button"
                    className={styles.citationPanelClose}
                    onClick={() => setOpenCitation(null)}
                  >
                    <X size={12} />
                  </button>
                </div>
                <p className={styles.citationPanelBody}>
                  {message.citations[openCitation].content}
                </p>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Document viewer modal */}
      {openDoc && (
        <DocumentModal
          docId={openDoc.docId}
          filename={openDoc.filename}
          highlightText={openDoc.highlightText}
          onClose={() => setOpenDoc(null)}
        />
      )}
    </div>
  );
}
